version: "3"
services:
  ids:
    build: ./dockerfiles/ids
    image: web_hybrid_ids_xss_sqli
    volumes:
      - ./codes/ids:/app
    tty: true
    ports:
      - 80:80
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: sh run.sh

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
