version: "3"
services:
  ids:
    build: ./dockerfiles/ids
    image: web_hybrid_ids_xss_sqli
    volumes:
      - ./codes/ids:/app
    tty: true
    ports:
      - 80:80
    depends_on:
      - postgres
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Taipei
    command: sh run.sh

  ids-frontend:
    build: ./dockerfiles/ids-frontend
    image: web_hybrid_ids_xss_sqli_frontend
    volumes:
      - "./codes/ids-frontend/build:/app"
    tty: true
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Taipei
    entrypoint: " http-server /app --port 8080 --cors"

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Taipei
