FROM python:3.10-bullseye
WORKDIR /app
# COPY requirment.txt /app/requirment.txt
RUN pip install fastapi==0.100.1
RUN pip install uvicorn[standard]==0.23.1
RUN pip install numpy==1.25.1
RUN pip install pandas==2.0.3
RUN pip install tflite-runtime==2.13.0
# RUN pip install -r requirment.txt